name = "Binnings"
uuid = "5e2e5b1a-4e10-4f16-bd66-f2628605f949"
authors = ["Riccardo PASINI"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
